# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RainyShinyWeather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RainyShinyWeather

  target 'RainyShinyWeatherTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire',
  :git => 'https://github.com/Alamofire/Alamofire.git'
  end

  target 'RainyShinyWeatherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
