# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'
#
# target 'RainyShinyWeather' do
#   # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#   use_frameworks!
#
#   # Pods for RainyShinyWeather
#   pod 'Alamofire',
#   :git => 'https://github.com/Alamofire/Alamofire.git'
#
#   target 'RainyShinyWeatherTests' do
#     inherit! :search_paths
#     # Pods for testing
#     pod 'Alamofire',
#   :git => 'https://github.com/Alamofire/Alamofire.git'
#   end
#
#   target 'RainyShinyWeatherUITests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
#
# end

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'RainyShinyWeather' do

    pod 'Alamofire', '~> 4.3'
end

target 'RainyShinyWeatherTests' do

    pod 'Alamofire', '~> 4.3'
end
